//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Congés
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_CongesEntities : DbContext
    {
        public Gestion_CongesEntities()
            : base("name=Gestion_CongesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stock_Conge> Stock_Conge { get; set; }
        public virtual DbSet<GesEmploye> GesEmployes { get; set; }
        public virtual DbSet<Conge> Conges { get; set; }
    }
}
