//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Congés
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandeConge
    {
        public int Matricule { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Type_Conge { get; set; }
        public Nullable<int> Duree { get; set; }
        public Nullable<System.DateTime> Date_Debut { get; set; }
        public string Remarques { get; set; }
    }
}
